apiVersion: v1
kind: Service
metadata:
  name: node-service 



spec:
  type: NodePort
  selector:
    app: firstimage


  ports:
    - port: 5000 #services
      targetPort: 80 #pod
      nodePort: 30001